CREATE SEQUENCE LINK_ID_SEQUENCE START WITH 1;

CREATE TABLE LINK
(
    LINK_ID          BIGINT,
    LINK_URL         VARCHAR,
    LINK_TITLE       VARCHAR,
    LINK_DESCRIPTION TEXT,

    PRIMARY KEY (LINK_ID),
    UNIQUE (LINK_URL)
);